apiVersion: v1
kind: ReplicationController
metadata:
  name: mynextbus-rc
spec:
  selector:
    name: web
    version: v0.1
  template:
    metadata:
      labels:
        name: web
        version: v0.1
    spec:
      containers:
      - name: mynextbus
        image: jchoksi/test1_img:0.1
        ports:
        - containerPort: 8081
